{% set name = "apache-airflow-providers-microsoft-azure" %}
{% set version = "3.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-microsoft-azure-{{ version }}.tar.gz
  sha256: 25908c91fc70c5612f61eafcd7821ba282a0841c0b7a383561116c856953a0bd
  patches:
    - 0001-remove-azure-keyvault-metapackage.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - apache-airflow >=2.1.0
    - azure-batch >=8.0.0
    - azure-cosmos >=4.0.0
    - azure-datalake-store >=0.0.45
    - azure-identity >=1.3.1
    # conda metapackage for azure-keyvault has tighter constraints than the pypi version
    # - azure-keyvault >=4.1.0
    - azure-keyvault-certificates >=4.1.0,<5
    - azure-keyvault-keys >=4.1.0,<5
    - azure-keyvault-secrets >=4.1.0,<5

    - azure-kusto-data >=0.0.43,<0.1
    - azure-mgmt-containerinstance >=1.5.0,<2.0
    - azure-mgmt-datafactory >=1.0.0,<2.0
    - azure-mgmt-datalake-store >=0.5.0
    - azure-mgmt-resource >=2.2.0
    - azure-storage-blob >=12.7.0,<12.9.0
    - azure-storage-common >=2.1.0
    - azure-storage-file >=2.1.0

test:
  imports:
    - airflow.providers.microsoft.azure
    - airflow.providers.microsoft.azure.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-microsoft-azure package
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
