{% set name = "apache-airflow-providers-microsoft-azure" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-microsoft-azure-{{ version }}.tar.gz
  sha256: f991ef79ff3b99e6fca7a814b80011a3675cf3f89a922c0583c64aa4d8773c6f
  patches:
    - 0001-remove-azure-keyvault-metapackage.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - azure-batch >=8.0.0
    - azure-cosmos >=4.0.0,<5
    - azure-datalake-store >=0.0.45
    - azure-identity >=1.3.1
    - azure-keyvault >=4.1.0
    - azure-kusto-data >=0.0.43,<0.1
    - azure-mgmt-containerinstance >=1.5.0,<2.0
    - azure-mgmt-datafactory >=1.0.0,<2.0
    - azure-mgmt-datalake-store >=0.5.0
    - azure-mgmt-resource >=2.2.0
    - azure-storage-blob >=12.7.0,<12.9.0
    - azure-storage-common >=2.1.0
    - azure-storage-file >=2.1.0

test:
  imports:
    - airflow.providers.microsoft.azure
    - airflow.providers.microsoft.azure.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Microsoft Azure for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
